### ISSUE TITLE
FEATURE: Env-specific logging

### ISSUE THREAD

**Issue by phptek** [silverstripe-labs/silverstripe-raygun#14]
Currently, the module isn't picky about what it reports or from where. The former is resolved by @chillu's filter example, the latter would be good to allow dev's to optionally enable Raygun logging on a per environment basis.

Yes it's easy to apply ad-hoc project-specific config, but it's messy in mysite/_config.php, so the ability apply something like this in project config would be better:

    RaygunLogWriter:
      environment:
        - test
        - live

This would obviously ensure that Raygun logged only in `test` and `live` environments. Something like the following in the module's own `_config.php` (Off the top of my head)

    $userDefinedEnvs = Config::inst()->get('RaygunLogWriter', 'environments');
    $enableOnLive = Director::isLive() && in_array('live', $userDefinedEnvs);
    $enableOnTest = Director::isTest() && in_array('test', $userDefinedEnvs);
    $enableOnDev = Director::isDev() && in_array('dev', $userDefinedEnvs);

    if(!empty($raygunAPIKey)) {
        // Enable on specific environments
        if(!$enableOnLive || !$enableOnTest || !$enableOnDev) {
            return;
        }
        ....
    }

**Comment by sminnee** [comment]
So, I would have thought that 19ff8ae24d6d7380bd7e627252cfb1c27bf9c8c2 allows for this; I'm a bit confused as to why it doesn't?

Failing that, it also supports an `_ss_environment.php` value.

**Comment by chillu** [comment]
Yeah, so as Sam says, that's already possible - closing.
